"""Reproducible classifier-training utilities."""

from .checkpoint import (
    CHECKPOINT_SCHEMA_VERSION,
    SNAPSHOT_SCHEMA_VERSION,
    atomic_torch_save,
    capture_rng_state,
    load_torch_artifact,
    restore_rng_state,
)
from .engine import (
    current_learning_rates,
    evaluate_classifier,
    is_better_validation,
    make_scheduler,
    train_one_epoch,
)
from .fork import (
    FORK_SCHEMA_VERSION,
    optimizer_family,
    restore_fork_checkpoint,
    transferred_state_digest,
    validate_fork_configuration,
)
from .runner import (
    fit_classifier,
    load_training_config,
    repository_git_state,
    resolve_training_config,
    run_training_from_config,
    seed_everything,
    validate_resume_configuration,
)
from .provenance import (
    PAIRED_PROVENANCE_SCHEMA_VERSION,
    create_initial_paired_provenance,
    observe_first_minibatch,
    validate_resume_paired_identity,
    validate_sibling_provenance,
)
from .task_f_plan import (
    TASK_F_APPROVAL_PACKET_SCHEMA_VERSION,
    TASK_F_PLAN_SCHEMA_VERSION,
    TASK_F_SNAPSHOT_EPOCHS,
    TASK_F_TRAINING_SCHEMA_VERSION,
    build_task_f_training_config,
    generate_approval_packet,
    generate_execution_only_pilot,
    generate_research_run_matrix,
    matrix_count_summary,
    research_aggregate_runs,
    validate_research_run_matrix,
    validate_no_protected_ood_references,
    validate_task_f_training_config,
)
from .telemetry import (
    UPDATE_TELEMETRY_SCHEMA_VERSION,
    UpdateTelemetryRecorder,
    candidate_optimizer_update,
    counterfactual_candidate_updates,
)

__all__ = [
    "CHECKPOINT_SCHEMA_VERSION",
    "SNAPSHOT_SCHEMA_VERSION",
    "atomic_torch_save",
    "capture_rng_state",
    "current_learning_rates",
    "evaluate_classifier",
    "FORK_SCHEMA_VERSION",
    "fit_classifier",
    "is_better_validation",
    "load_torch_artifact",
    "load_training_config",
    "make_scheduler",
    "matrix_count_summary",
    "optimizer_family",
    "restore_rng_state",
    "restore_fork_checkpoint",
    "repository_git_state",
    "resolve_training_config",
    "run_training_from_config",
    "seed_everything",
    "train_one_epoch",
    "transferred_state_digest",
    "TASK_F_APPROVAL_PACKET_SCHEMA_VERSION",
    "TASK_F_PLAN_SCHEMA_VERSION",
    "TASK_F_SNAPSHOT_EPOCHS",
    "TASK_F_TRAINING_SCHEMA_VERSION",
    "PAIRED_PROVENANCE_SCHEMA_VERSION",
    "UPDATE_TELEMETRY_SCHEMA_VERSION",
    "UpdateTelemetryRecorder",
    "build_task_f_training_config",
    "candidate_optimizer_update",
    "counterfactual_candidate_updates",
    "create_initial_paired_provenance",
    "generate_approval_packet",
    "generate_execution_only_pilot",
    "generate_research_run_matrix",
    "observe_first_minibatch",
    "research_aggregate_runs",
    "validate_research_run_matrix",
    "validate_no_protected_ood_references",
    "validate_resume_paired_identity",
    "validate_sibling_provenance",
    "validate_task_f_training_config",
    "validate_fork_configuration",
    "validate_resume_configuration",
]
